spring:
  application:
    name: ali-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8081
server:
  port: 8081

feign:
  sentinel:
    enabled: true
