spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/givking/test
          search-paths: /cloud-config/src/main/resources/test
          username: givking
          password: g125311899
#  profiles:
#    active: native
server:
  port: 8005
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.2.107:9999/eureka/
  #      defaultZone: http://user:123456@localhost:8080/eureka/      #服务注册中信地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心